# Generated by Django 2.0.7 on 2019-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190804_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('open_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
                ('games_total_count', models.CharField(max_length=100)),
                ('games_available_count', models.CharField(max_length=100)),
            ],
        ),
    ]
