# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('open_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
                ('games_total_count', models.CharField(max_length=100)),
                ('games_available_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VenueForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
