# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apad_phase2_app', '0002_delete_venueform'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_new_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cat_id', models.CharField(max_length=100)),
                ('venue_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('host_flag', models.CharField(max_length=100)),
                ('member_flag', models.CharField(max_length=100)),
                ('sports_Cat_id', models.CharField(max_length=100)),
                ('event_desc', models.CharField(max_length=100, null=True)),
                ('capacity_avail', models.CharField(max_length=100)),
            ],
        ),
    ]
