# Generated by Django 2.0.7 on 2019-08-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_event_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100)),
                ('player_count', models.IntegerField()),
                ('equip_req_flag', models.CharField(max_length=10)),
                ('sport_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='add_venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('open_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
                ('games_total_count', models.CharField(max_length=100)),
                ('games_available_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=8)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
