# Generated by Django 2.0.7 on 2019-08-08 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psevents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_new_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('host_flag', models.CharField(max_length=100, null=True)),
                ('member_flag', models.CharField(max_length=100, null=True)),
                ('event_desc', models.CharField(max_length=100, null=True)),
                ('capacity_avail', models.CharField(max_length=100)),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='psevents.add_event_cat')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='psevents.add_sports')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='psevents.add_venue')),
            ],
        ),
    ]
