# Generated by Django 2.0.7 on 2019-08-08 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psevents', '0002_add_new_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_event',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
