# Generated by Django 2.0.7 on 2019-08-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psevents', '0003_auto_20190808_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_event',
            name='host_flag',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_new_event',
            name='member_flag',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
